project:
  type: book
  output-dir: output_0
number-sections: true
crossref:
  fig-prefix: Figura
  custom:
    - kind: float
      reference-prefix: Figura
      key: figu
execute:
  echo: false
  warning: false
  message: false
callout-appearance: simple
book:
  title:  Sisvar - Manual do Usu치rio
  description: Exemplos pr치ticos de uso
  favicon: assets/ciga-logo.svg
  sidebar:
    logo: assets/ciga.png
    align: left
    collapse-level: 1
    search: true
  page-footer:
    center: CIGA | Sisvar - Manual do Usu치rio
  chapters:
    - index.qmd
    - 01_dicionario.qmd
    - 02_usuarios.qmd
    - 03_convidados.qmd
    - 04_auditorias.qmd
    - 05_tacs.qmd
    - 06_estruturas_geotecnicas.qmd
format:
  html:
    theme: [cosmo, assets/custom.scss]
    mainfont: Arial
    toc: true
    toc-title: "Sum치rio"
    toc-depth: 3
    linkcolor: "#00353E"
    logo: assets/ciga.png
    css: assets/styles.css
