project:
  type: book
  output-dir: output
number-sections: true
crossref:
  fig-prefix: Figura
  custom:
    - kind: float
      reference-prefix: Figura
      key: figu
execute:
  echo: false
  warning: false
  message: false
callout-appearance: simple
book:
  title:  Sisvar - Manual do Usu치rio
  description: Exemplos pr치ticos de uso
  favicon: assets/ciga-logo.svg
  downloads: pdf
  sidebar:
    logo: assets/ciga.png
    align: left
    collapse-level: 1
    search: true
  page-footer:
    center: CIGA | Sisvar - Manual do Usu치rio

  chapters:
    - index.qmd
    - 01_dicionario.qmd
    - 02_dashboard.qmd
    - 03_usuarios.qmd
    - 04_convidados.qmd
    - 05_auditorias.qmd
    - 06_tacs.qmd
    - 07_estruturas_geotecnicas.qmd
    - 08_empreendedores.qmd

format:
  html:
    theme: [cosmo, assets/custom.scss]
    mainfont: Arial
    toc: true
    toc-title: "Sum치rio"
    toc-depth: 3
    linkcolor: "#00353E"
    logo: assets/ciga.png
    css: assets/styles.css

  pdf:
    documentclass: book
    toc: true
    toc-depth: 2
    papersize: a4
    mainfont: Arial
    geometry: [top=30mm, bottom=30mm, left=25mm, right=25mm]
    linkcolor: "#00353E"
