project:
  type: book
  output-dir: docs
number-sections: true
crossref:
  fig-prefix: Figura
  custom:
    - kind: float
      reference-prefix: Figura
      key: figu
      latex-env: Figura
execute:
  echo: false
  warning: false
  message: false
callout-appearance: simple
book:
  title:  Sisvar - Manual do Usuário - Perfil Instituição
  description: Exemplos práticos de uso
  favicon: assets/ciga-logo.svg
  sidebar:
    logo: assets/ciga.png
    align: left
    collapse-level: 1
    search: true
  page-footer:
    center: CIGA | Sisvar
  chapters:
    - index.qmd
    - 01_dicionario.qmd
    - 02_dashboard.qmd
    - 03_usuarios.qmd
    - 04_convidados.qmd
    - 05_auditorias.qmd
    - 06_tacs.qmd
    - 07_estruturas_geotecnicas.qmd
    - 08_empreendedores.qmd
format:
  html:
    theme: [cosmo, assets/custom.scss]
    mainfont: Arial
    toc: true
    toc-title: "Sumário"
    toc-depth: 3
    linkcolor: "#00353E"
    logo: assets/ciga.png
    css: assets/styles.css
  pdf:
    documentclass: report
    mainfont: Arial
    geometry:
      - margin=2.5cm
    toc: true
    toc-title: "Sumário"
    toc-depth: 3
    colorlinks: true
    latex-engine: xelatex
    header-includes:
      - \renewcommand{\chaptername}{Capítulo}
      - \renewcommand{\thechapter}{\arabic{chapter}}
