name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Prepare gh-pages branch
      run: |
        # Cria a branch gh-pages ou a reseta se já existir
        git checkout -B gh-pages
        # Remove apenas as pastas de destino para manter o repositório intacto
        rm -rf gestor instituicao responsavel

    - name: Copy content from docs folders
      run: |
        # Cria as pastas e copia o conteúdo de cada subpasta docs
        mkdir -p gestor instituicao responsavel
        cp -r manual_gestor/docs/* gestor/
        cp -r manual_instituicao/docs/* instituicao/
        cp -r manual_responsavel/docs/* responsavel/

    - name: Commit and push changes
      run: |
        git add gestor instituicao responsavel
        git commit -m "Deploy manuals from docs folders"
        git push origin gh-pages --force
