name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Prepare gh-pages branch
      run: |
        # Cria a branch gh-pages se ela não existir
        git checkout -B gh-pages

    - name: Rename folders and commit
      run: |
        # Renomeia as pastas conforme necessário
        mv manual_gestor gestor
        mv manual_instituicao instituicao
        mv manual_responsavel responsavel
        # Adiciona e comita as mudanças
        git add gestor instituicao responsavel
        git commit -m "Deploy manuals"

    - name: Push to gh-pages
      run: |
        git push origin gh-pages --force
