name: Update Manual Branches

on:
  push:
    branches:
      - main

jobs:
  update_manual_gestor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout manual_gestor branch (or create if it doesn't exist)
        run: |
          git fetch origin
          # Cria ou faz checkout na branch manual_gestor
          git checkout -B manual_gestor origin/manual_gestor || git checkout --orphan manual_gestor

      - name: Copy output_gestor to manual_gestor
        run: |
          # Copia apenas os arquivos de output_gestor para a branch manual_gestor
          cp -r manual_gestor/output_gestor/* ./manual_gestor/

      - name: Commit and push changes to manual_gestor
        run: |
          git add .
          git commit -m "Update manual_gestor with the latest output_gestor"
          git push origin manual_gestor

  update_manual_instituicao:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout manual_instituicao branch (or create if it doesn't exist)
        run: |
          git fetch origin
          # Cria ou faz checkout na branch manual_instituicao
          git checkout -B manual_instituicao origin/manual_instituicao || git checkout --orphan manual_instituicao

      - name: Copy output_instituicao to manual_instituicao
        run: |
          # Copia apenas os arquivos de output_instituicao para a branch manual_instituicao
          cp -r manual_instituicao/output_instituicao/* ./manual_instituicao/

      - name: Commit and push changes to manual_instituicao
        run: |
          git add .
          git commit -m "Update manual_instituicao with the latest output_instituicao"
          git push origin manual_instituicao

  update_manual_responsavel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout manual_responsavel branch (or create if it doesn't exist)
        run: |
          git fetch origin
          # Cria ou faz checkout na branch manual_responsavel
          git checkout -B manual_responsavel origin/manual_responsavel || git checkout --orphan manual_responsavel

      - name: Copy output_responsavel to manual_responsavel
        run: |
          # Copia apenas os arquivos de output_responsavel para a branch manual_responsavel
          cp -r manual_responsavel/output_responsavel/* ./manual_responsavel/

      - name: Commit and push changes to manual_responsavel
        run: |
          git add .
          git commit -m "Update manual_responsavel with the latest output_responsavel"
          git push origin manual_responsavel
